name:                fuji
version:             0.1.0.0
github:              "eirikhalvard/fuji"
license:             BSD3
author:              "Eirik Halvard Sæther"
maintainer:          "eirik.halvard.95@gmail.com"
copyright:           "2021 Eirik Halvard Sæther"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eirikhalvard/fuji#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- time
- optparse-applicative
- unix-compat
- filepath
- containers
- extra

library:
  source-dirs: src

executables:
  fuji:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fuji

tests:
  fuji-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fuji
