#!/usr/bin/env osascript

# format of output:
# |||albumname;;;name1;;;name2|||album2;;;n1;;;n2;;;n3

tell application "Photos"
    set output to ""
    set targetAlbumNames to {"idafam", "Bangers", "Backgrounds", "Venner", "Street"}

    repeat with albumName in targetAlbumNames
        set i to (get album albumName)
        set tFolder to (the POSIX path of (path to pictures folder) & "Export/" & albumName) as POSIX file as text
        repeat 1 times
            try
                set theimages to get media items of i
            on error line number num
                display dialog "Error on line number " & num
            end try
            set output to output & "|||" & (get name of i)
            repeat with image in theimages
                try
                    set imgFilename to the ({filename of image})
                    set output to output & ";;;" & imgFilename
                end try
            end repeat
        end repeat
    end repeat
end tell

return output
